#!/usr/bin/env bash
# clean_test_artifacts.sh — Remove generated build artifacts from test runs.
#
# Cleans VCS simulation outputs, rtl_trace DB files, Python caches,
# build directories, and session stores — but NOT .venv or source files.
#
# Usage:
#   ./clean_test_artifacts.sh          # dry-run (print what would be removed)
#   ./clean_test_artifacts.sh -f       # actually delete
#   ./clean_test_artifacts.sh -s       # also clean standalone_trace profile logs

set -euo pipefail

FORCE=0
EXTRA_STANDALONE=0

usage() {
    echo "Usage: $0 [-f] [-s] [-h]"
    echo ""
    echo "  -f    Actually delete files (default is dry-run)"
    echo "  -s    Also clean standalone_trace profile/mem logs"
    echo "  -h    Show this help"
    exit 0
}

while getopts "fsh" opt; do
    case "$opt" in
        f) FORCE=1 ;;
        s) EXTRA_STANDALONE=1 ;;
        h) usage ;;
        *) usage ;;
    esac
done

REMOVAL_COUNT=0

remove_path() {
    local path="$1"
    if [ ! -e "$path" ]; then
        return 0
    fi
    local size
    if [ -d "$path" ]; then
        size=$(du -sh "$path" 2>/dev/null | cut -f1 || echo "?")
    else
        size=$(ls -lh "$path" 2>/dev/null | awk '{print $5}' || echo "?")
    fi
    REMOVAL_COUNT=$((REMOVAL_COUNT + 1))
    if [ "$FORCE" -eq 1 ]; then
        rm -rf "$path"
        echo "  [DEL] $path  ($size)"
    else
        echo "  [DRY] $path  ($size)"
    fi
}

if [ "$FORCE" -eq 0 ]; then
    echo "=== DRY RUN (use -f to actually delete) ==="
    echo ""
fi

# --- 1. test_cases/tcXX: VCS simulation artifacts ---
# These are generated by run_test.sh: vcs simulation, rtl_trace compile, etc.
# Only clean known artifact names, never source files (.sv, .py, .sh, .f, .md).

echo "--- test_cases/: VCS and rtl_trace build artifacts ---"

for tcdir in test_cases/tc*/; do
    [ -d "$tcdir" ] || continue

    # VCS compiled C source
    remove_path "${tcdir}csrc"
    # VCS simulation binary
    remove_path "${tcdir}simv"
    # VCS simulation data
    remove_path "${tcdir}simv.daidir"
    # VCS compile log
    remove_path "${tcdir}vcs.log"
    # Generated Verilog (preprocessor output from rtl_trace compile)
    remove_path "${tcdir}rtl"

    # rtl_trace DB files (tcXX.db) and their .meta sidecars
    for db in "${tcdir}"*.db; do
        [ -f "$db" ] || continue
        remove_path "$db"
    done
    for meta in "${tcdir}"*.db.meta; do
        [ -f "$meta" ] || continue
        remove_path "$meta"
    done
done

# Top-level test_cases DB meta
remove_path "test_cases/rtl_trace.db.meta"

# --- 2. standalone_trace build artifacts ---

echo ""
echo "--- standalone_trace: build artifacts ---"
remove_path "standalone_trace/build"

if [ "$EXTRA_STANDALONE" -eq 1 ]; then
    echo "  (also cleaning profile logs)"
    for f in standalone_trace/slang_*_opt*.log \
             standalone_trace/slang_mem_profile*.log \
             standalone_trace/slang_latest_opt_run.log \
             standalone_trace/slang_old_opt_run.log; do
        [ -f "$f" ] || continue
        remove_path "$f"
    done
fi

# --- 3. waveform_explorer build artifacts ---

echo ""
echo "--- waveform_explorer: build artifacts ---"
remove_path "waveform_explorer/build"

# --- 4. Python __pycache__ (project dirs only, NOT .venv) ---

echo ""
echo "--- Python __pycache__ (project dirs only) ---"
for cachedir in $(find . \
    -path ./.venv -prune -o \
    -path ./standalone_trace/third_party -prune -o \
    -type d -name "__pycache__" -print 2>/dev/null); do
    remove_path "$cachedir"
done

# --- 5. agent_debug_automation session store ---

echo ""
echo "--- agent_debug_automation: session store ---"
remove_path "agent_debug_automation/.session_store"

# --- 6. Misc transient files ---

echo ""
echo "--- Misc transient files ---"
[ -f "conversation.log" ] && remove_path "conversation.log"
[ -d "standalone_trace/third_party/bak" ] && remove_path "standalone_trace/third_party/bak"

# --- Summary ---

echo ""
if [ "$FORCE" -eq 1 ]; then
    echo "=== DONE: removed $REMOVAL_COUNT paths ==="
else
    echo "=== DRY RUN: $REMOVAL_COUNT paths would be removed ==="
    echo "    Run with -f to actually delete."
fi
